# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View/metricsGUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(573, 655)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.hub1 = QtWidgets.QRadioButton(self.groupBox)
        self.hub1.setChecked(True)
        self.hub1.setObjectName("hub1")
        self.gridLayout_6.addWidget(self.hub1, 1, 0, 1, 1)
        self.hub2 = QtWidgets.QRadioButton(self.groupBox)
        self.hub2.setObjectName("hub2")
        self.gridLayout_6.addWidget(self.hub2, 2, 0, 1, 1)
        self.hub3 = QtWidgets.QRadioButton(self.groupBox)
        self.hub3.setObjectName("hub3")
        self.gridLayout_6.addWidget(self.hub3, 3, 0, 1, 1)
        self.canada = QtWidgets.QRadioButton(self.groupBox)
        self.canada.setObjectName("canada")
        self.gridLayout_6.addWidget(self.canada, 3, 1, 1, 1)
        self.hub5 = QtWidgets.QRadioButton(self.groupBox)
        self.hub5.setObjectName("hub5")
        self.gridLayout_6.addWidget(self.hub5, 2, 1, 1, 1)
        self.hub4 = QtWidgets.QRadioButton(self.groupBox)
        self.hub4.setObjectName("hub4")
        self.gridLayout_6.addWidget(self.hub4, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.metricsSelector = QtWidgets.QComboBox(self.groupBox_2)
        self.metricsSelector.setObjectName("metricsSelector")
        self.metricsSelector.addItem("")
        self.metricsSelector.addItem("")
        self.metricsSelector.addItem("")
        self.metricsSelector.addItem("")
        self.metricsSelector.addItem("")
        self.gridLayout_4.addWidget(self.metricsSelector, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.fileDialogButton = QtWidgets.QPushButton(self.groupBox_3)
        self.fileDialogButton.setObjectName("fileDialogButton")
        self.gridLayout.addWidget(self.fileDialogButton, 0, 3, 1, 1)
        self.fileSelectInput = QtWidgets.QLineEdit(self.groupBox_3)
        self.fileSelectInput.setReadOnly(True)
        self.fileSelectInput.setObjectName("fileSelectInput")
        self.gridLayout.addWidget(self.fileSelectInput, 0, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.importFileButton = QtWidgets.QPushButton(self.groupBox_3)
        self.importFileButton.setObjectName("importFileButton")
        self.gridLayout_5.addWidget(self.importFileButton, 0, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_5)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.removeButton = QtWidgets.QPushButton(self.groupBox_3)
        self.removeButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeButton.sizePolicy().hasHeightForWidth())
        self.removeButton.setSizePolicy(sizePolicy)
        self.removeButton.setObjectName("removeButton")
        self.gridLayout_7.addWidget(self.removeButton, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 0, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_7)
        self.filePathList = QtWidgets.QListWidget(self.groupBox_3)
        self.filePathList.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.filePathList.setMidLineWidth(0)
        self.filePathList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.filePathList.setAlternatingRowColors(True)
        self.filePathList.setObjectName("filePathList")
        self.verticalLayout_5.addWidget(self.filePathList)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.fileExportPathInput = QtWidgets.QLineEdit(self.groupBox_3)
        self.fileExportPathInput.setObjectName("fileExportPathInput")
        self.gridLayout_2.addWidget(self.fileExportPathInput, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.fileExportDialog = QtWidgets.QPushButton(self.groupBox_3)
        self.fileExportDialog.setObjectName("fileExportDialog")
        self.gridLayout_2.addWidget(self.fileExportDialog, 0, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.filePathList.raise_()
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.exportButton = QtWidgets.QPushButton(self.centralwidget)
        self.exportButton.setObjectName("exportButton")
        self.gridLayout_3.addWidget(self.exportButton, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 573, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Metrics Aggregator"))
        self.groupBox.setTitle(_translate("MainWindow", "Region "))
        self.hub1.setText(_translate("MainWindow", "Hub 1"))
        self.hub2.setText(_translate("MainWindow", "Hub 2"))
        self.hub3.setText(_translate("MainWindow", "Hub 3"))
        self.canada.setText(_translate("MainWindow", "Canada"))
        self.hub5.setText(_translate("MainWindow", "Hub 5"))
        self.hub4.setText(_translate("MainWindow", "Hub 4"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Metrics Type"))
        self.label_3.setText(_translate("MainWindow", "Ensure All Documents Match"))
        self.metricsSelector.setItemText(0, _translate("MainWindow", "Select Metric Type"))
        self.metricsSelector.setItemText(1, _translate("MainWindow", "Action Tracking System"))
        self.metricsSelector.setItemText(2, _translate("MainWindow", "Compliance Calendar"))
        self.metricsSelector.setItemText(3, _translate("MainWindow", "Near Miss Reporting"))
        self.metricsSelector.setItemText(4, _translate("MainWindow", "Training"))
        self.groupBox_3.setTitle(_translate("MainWindow", "File Selection"))
        self.label_2.setText(_translate("MainWindow", "Select File to Add to Report"))
        self.fileDialogButton.setText(_translate("MainWindow", "Select File"))
        self.importFileButton.setText(_translate("MainWindow", "Import File"))
        self.removeButton.setText(_translate("MainWindow", "Remove File"))
        self.label_4.setText(_translate("MainWindow", "Current Files To Aggregate:"))
        self.label.setText(_translate("MainWindow", "Export Aggregate File Location"))
        self.fileExportDialog.setText(_translate("MainWindow", "Select Location"))
        self.exportButton.setText(_translate("MainWindow", "Export"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
